# Generated by Django 5.1 on 2026-04-04 03:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='workflow_json',
            new_name='actions',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='name',
            new_name='workflow_name',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),
        migrations.AddField(
            model_name='workflow',
            name='action_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='saved', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('html_report', models.TextField(blank=True, null=True)),
                ('json_report', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.workflow')),
            ],
            options={
                'db_table': 'api_workflow_report',
            },
        ),
    ]
