# Generated by Django 5.1 on 2026-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_workflow_json_workflow_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='plan_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='plan_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
