# Generated by Django 5.1 on 2026-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_billing_plan_end_billing_plan_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='plan_end',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='plan_start',
        ),
        migrations.AddField(
            model_name='billing',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='price_per_action',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
