# Generated by Django 5.1 on 2026-04-04 07:11

import api.Workflow.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_billing_plan_end_remove_billing_plan_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowreport',
            name='html_report_file',
            field=models.FileField(blank=True, null=True, upload_to=api.Workflow.model.report_upload_path),
        ),
    ]
